version: "3.9"

services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    restart: always
